// Try Catch é um recurso famoso nas linguagens de programação

//Onde tentamos executar algo em try, e se um erro ocorrer ele cai no bloco do catch

//útil tanto para debug, como tambem no desenvolvimento de uma aplicação sólida

try{
    const soma = x+y
} catch(error){
    console.log(`Erro no programar ${error}`)
}